
especialidades = [
    ('Nefrologo','Nefrologo'),
    ('Neurologo','Neurologo'),
    ('Cardiologo clinico','Cardiologo clinico'),
    ('Cardiologo hemodinamista','Cardiologo hemodinamista'),
    ('Cardiologo arritmiologo','Cardiologo arritmiologo'),
    ('Cardiologo Pediatra','Cardiologo Pediatra'),
    ('Neumonologo','Neumonologo'),
    ('Neumonologo pediatra','Neumonologo pediatra'),
    ('Medico internista y diabetologo','Medico internista y diabetologo'),
    ('Medico emergenciologo','Medico emergenciologo'),
    ('Medico general','Medico general'),
    ('Medico cirujano','Medico cirujano'),
    ('Medico ocupacional','Medico ocupacional'),
    ('Medio urologo','Medio urologo'),
    ('Medico gastroenterologo','Medico gastroenterologo'),
    ('Medico otorrinolaringologo','Medico otorrinolaringologo'),
    ('Medico Angiologo','Medico Angiologo'),
    ('Medico imagenologo','Medico imagenologo'),
    ('Medico cirujano especialista en manos','Medico cirujano especialista en manos'),
    ('Medico traumatologo','Medico traumatologo'),
]