servicios = {
    'Neumologia pediátrica':'Neumologia pediátrica',
    'Neumologia':'Neumologia',
    'Cardiologia':'Cardiologia',
    'Cardiologia pediátrica':'Cardiologia pediátrica',
    'Gastroenterologia':'Gastroenterologia',
    'Otorrinolaringologia':'Otorrinolaringologia',
    'Medicina interna':'Medicina interna',
    'Diabetologia':'Diabetologia',
    'Medicina Ocupacional':'Medicina Ocupacional',
    'Medicina General':'Medicina General',
    'Medicina de Emergencia':'Medicina de Emergencia',
    'Urologia':'Urologia',
    'Cardiologia intervencionista':'Cardiologia intervencionista',
    'Cardiologia (arritmiologo)':'Cardiologia (arritmiologo)',
    'Cardiologia (hemodinamista)':'Cardiologia (hemodinamista)',
    'Angiologia':'Angiologia',
    'Medicina de Imágenes':'Medicina de Imágenes'
}

especialidades = [
    ('Nefrologo','Nefrologo'),
    ('Neurologo','Neurologo'),
    ('Cardiologo clinico','Cardiologo clinico'),
    ('Cardiologo hemodinamista','Cardiologo hemodinamista'),
    ('Cardiologo arritmiologo','Cardiologo arritmiologo'),
    ('Cardiologo Pediatra','Cardiologo Pediatra'),
    ('Neumonologo','Neumonologo'),
    ('Neumonologo pediatra','Neumonologo pediatra'),
    ('Medico internista y diabetologo','Medico internista y diabetologo'),
    ('Medico emergenciologo','Medico emergenciologo'),
    ('Medico general','Medico general'),
    ('Medico cirujano','Medico cirujano'),
    ('Medico ocupacional','Medico ocupacional'),
    ('Medio urologo','Medio urologo'),
    ('Medico gastroenterologo','Medico gastroenterologo'),
    ('Medico otorrinolaringologo','Medico otorrinolaringologo'),
    ('Medico Angiologo','Medico Angiologo'),
    ('Medico imagenologo','Medico imagenologo'),
    ('Medico cirujano especialista en manos','Medico cirujano especialista en manos'),
    ('Medico traumatologo','Medico traumatologo'),
]

metodos_pago = (
    ('Pago móvil', 'Pago móvil'), 
    ('Transferencia', 'Transferencia'), 
    ('Zelle', 'Zelle'), 
    ('Débito', 'Débito'),
    ('Efectivo BS', 'Efectivo BS'),
    ('Efectivo Dólares', 'Efectivo Dólares'), 
    ('Efectivo Euros', 'Efectivo Euros'),
)