# Generated by Django 4.2 on 2023-11-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medico",
            name="nacionalidad",
            field=models.CharField(
                blank=True,
                choices=[("E-", "Extranjero"), ("V-", "Venezolano")],
                default="V-",
                max_length=2,
                null=True,
            ),
        ),
    ]
