# Generated by Django 4.2 on 2023-11-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citas", "0002_medico_nacionalidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medico",
            name="nacionalidad",
            field=models.CharField(
                blank=True,
                choices=[("E-", "E-"), ("V-", "V-")],
                default="V-",
                max_length=2,
                null=True,
            ),
        ),
    ]
