# Generated by Django 4.2 on 2023-10-29 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("citas", "0002_cita_estado_alter_medico_especialidad_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cita",
            name="medico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="citas.medico"
            ),
        ),
    ]
