# Generated by Django 4.2 on 2023-10-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citas", "0004_medico_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medico",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[("AC", "Habilitado"), ("DE", "Desabilitado")],
                default="AC",
                max_length=2,
                null=True,
            ),
        ),
    ]
