# Generated by Django 4.2 on 2023-11-26 16:52

import apps.presupuestos.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("citas", "0001_initial"),
        ("anuncios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True,
                        choices=[("AC", "Habilitado"), ("DE", "Desabilitado")],
                        default="AC",
                        max_length=2,
                        null=True,
                    ),
                ),
                ("nombre_serv", models.CharField(max_length=50)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("precio_serv", models.FloatField(default=0.0)),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="citas.medico"
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio",
                "verbose_name_plural": "Servicios",
                "permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Presupuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True,
                        choices=[("AC", "Habilitado"), ("DE", "Desabilitado")],
                        default="AC",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("Pago móvil", "Pago móvil"),
                            ("Transferencia", "Transferencia"),
                            ("Zelle", "Zelle"),
                            ("Débito", "Débito"),
                            ("Efectivo BS", "Efectivo BS"),
                            ("Efectivo Dólares", "Efectivo Dólares"),
                            ("Efectivo Euros", "Efectivo Euros"),
                        ],
                        default="Pago móvil",
                        max_length=50,
                    ),
                ),
                ("total", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "fecha",
                    models.DateField(
                        blank=True, default=datetime.date.today, null=True
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True,
                        default=apps.presupuestos.models.obtener_fecha_vencimiento,
                        null=True,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="anuncios.usuario",
                    ),
                ),
                ("servicio", models.ManyToManyField(to="presupuestos.servicio")),
            ],
            options={
                "verbose_name": "Presupuesto",
                "verbose_name_plural": "Presupuestos",
                "permissions": [],
            },
        ),
    ]
