# Generated by Django 4.2 on 2023-10-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presupuestos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="presupuesto",
            name="estado",
            field=models.CharField(
                choices=[("AC", "Habilitado"), ("DE", "Desabilitado")],
                default="AC",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="estado",
            field=models.CharField(
                choices=[("AC", "Habilitado"), ("DE", "Desabilitado")],
                default="AC",
                max_length=2,
            ),
        ),
    ]
