# Generated by Django 4.2 on 2023-11-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presupuestos", "0002_alter_servicio_metodo_pago"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicio",
            name="metodo_pago",
        ),
        migrations.AddField(
            model_name="presupuesto",
            name="metodo_pago",
            field=models.CharField(
                choices=[
                    ("Pago móvil", "Pago móvil"),
                    ("Transferencia", "Transferencia"),
                    ("Zelle", "Zelle"),
                    ("Débito", "Débito"),
                    ("Efectivo BS", "Efectivo BS"),
                    ("Efectivo Dólares", "Efectivo Dólares"),
                    ("Efectivo Euros", "Efectivo Euros"),
                ],
                default="Pago móvil",
                max_length=50,
            ),
        ),
    ]
