# Generated by Django 4.2 on 2023-11-05 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("presupuestos", "0003_remove_servicio_metodo_pago_presupuesto_metodo_pago"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="presupuesto",
            name="servicio",
        ),
        migrations.AddField(
            model_name="presupuesto",
            name="total",
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name="DetallePresupuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("AC", "Habilitado"), ("DE", "Desabilitado")],
                        default="AC",
                        max_length=2,
                    ),
                ),
                ("total", models.FloatField(default=0.0)),
                (
                    "presupuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="presupuestos.presupuesto",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="presupuestos.servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle Presupuesto",
                "verbose_name_plural": "Detalle Presupuestos",
                "permissions": [],
            },
        ),
    ]
