# Generated by Django 4.2 on 2023-11-05 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presupuestos", "0005_presupuesto_fecha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detallepresupuesto",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[("AC", "Habilitado"), ("DE", "Desabilitado")],
                default="AC",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="presupuesto",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[("AC", "Habilitado"), ("DE", "Desabilitado")],
                default="AC",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="presupuesto",
            name="fecha",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[("AC", "Habilitado"), ("DE", "Desabilitado")],
                default="AC",
                max_length=2,
                null=True,
            ),
        ),
    ]
