# Generated by Django 4.2 on 2023-11-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presupuestos", "0006_alter_detallepresupuesto_estado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="presupuesto",
            name="servicio",
            field=models.ManyToManyField(to="presupuestos.servicio"),
        ),
        migrations.DeleteModel(
            name="DetallePresupuesto",
        ),
    ]
