# Generated by Django 4.2 on 2023-11-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presupuestos", "0007_presupuesto_servicio_delete_detallepresupuesto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presupuesto",
            name="total",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
