# Generated by Django 4.2 on 2023-11-18 18:34

import apps.presupuestos.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presupuestos", "0008_alter_presupuesto_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="presupuesto",
            name="fecha_vencimiento",
            field=models.DateField(
                blank=True,
                default=apps.presupuestos.models.obtener_fecha_vencimiento,
                null=True,
            ),
        ),
    ]
