# Generated by Django 4.2 on 2023-11-19 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('presupuestos', '0009_presupuesto_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='citas.medico'),
        ),
    ]
