# Generated by Django 4.2 on 2023-11-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anuncios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anuncios",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[("AC", "Habilitado"), ("DE", "Desabilitado")],
                default="AC",
                max_length=2,
                null=True,
            ),
        ),
    ]
