# Generated by Django 4.2 on 2023-11-11 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("anuncios", "0002_alter_anuncios_estado"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={
                "permissions": [
                    ("requiere_usuario", "requiero nivel usuario"),
                    ("requiere_secretria", "requiero nivel secretaria"),
                    ("requiere_admin", "requiero nivel admin"),
                ],
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
    ]
