# Generated by Django 4.2 on 2023-11-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anuncios", "0003_alter_usuario_nacionalidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="nacionalidad",
            field=models.CharField(
                blank=True,
                choices=[("E", "E"), ("V", "V")],
                default="V",
                max_length=2,
                null=True,
            ),
        ),
    ]
