# Generated by Django 4.2 on 2023-11-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0004_alter_usuario_nacionalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncios',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
