# Generated by Django 4.2 on 2023-11-28 23:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anuncios', '0001_initial'),
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_created=True, default=datetime.datetime.now)),
                ('titulo', models.CharField(max_length=50)),
                ('leido', models.BooleanField(default=False)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.cita')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.usuario')),
            ],
        ),
    ]
