# Generated by Django 4.2 on 2023-11-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("historia", models.TextField(blank=True, null=True)),
                ("mision", models.TextField(blank=True, null=True)),
                ("vision", models.TextField(blank=True, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("direccion", models.CharField(blank=True, max_length=80, null=True)),
                ("telefono", models.CharField(blank=True, max_length=11, null=True)),
                ("telefono2", models.CharField(blank=True, max_length=11, null=True)),
                ("telefono3", models.CharField(blank=True, max_length=11, null=True)),
                ("telefono4", models.CharField(blank=True, max_length=11, null=True)),
                ("whatsapp", models.URLField(blank=True, max_length=150, null=True)),
                ("instagram", models.URLField(blank=True, max_length=150, null=True)),
                ("instagram2", models.URLField(blank=True, max_length=150, null=True)),
                ("instagram3", models.URLField(blank=True, max_length=150, null=True)),
                ("instagram4", models.URLField(blank=True, max_length=150, null=True)),
                ("instagram5", models.URLField(blank=True, max_length=150, null=True)),
                ("facebook", models.URLField(blank=True, max_length=150, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Landing Page",
                "verbose_name_plural": "Landing Page",
                "permissions": [],
            },
        ),
    ]
