# Generated by Django 4.2 on 2023-11-12 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Galeria',
        ),
    ]
