# Generated by Django 4.2 on 2023-11-13 00:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("landingpage", "0002_delete_galeria"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landingpage",
            name="precio_serv",
        ),
    ]
